---

- name: Setup Environment and Configure Certbot
  hosts: all
  vars:
    domain_name: "{{ domain_name | default('') }}"
    email: "{{ email | default('') }}"
  become: true

  pre_tasks:
    - name: Validate DOMAIN_NAME and EMAIL are set via extra-vars
      ansible.builtin.fail:
        msg: "Variable {{ item }} is not set!"
      with_items:
        - domain_name
        - email
      when: item == ""

    - name: Update the package manager cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600  # Cache validity set to 1 hour

  tasks:
    - name: Install Docker (using a role)
      ansible.builtin.include_role:
        name: bsmeding.docker  # Docker installation handled by external role

    - name: Ensure /app directory exists
      ansible.builtin.file:
        path: /app
        state: directory  # Create /app directory if it doesn't exist
        mode: '0755'
        owner: root
        group: root

    - name: Copy the entire directory to /app
      ansible.builtin.copy:
        src: /home/ubuntu/ansible/dependencies
        dest: /app/
        owner: root
        group: root
        mode: '0755'

    - name: Move docker-compose.yml to parent directory
      ansible.builtin.command:
        cmd: mv /app/dependencies/docker-compose-monitoring.yaml /app/docker-compose-monitoring.yaml
      args:
        creates: /app/docker-compose-monitoring.yaml

    - name: Install Certbot and its dependencies
      ansible.builtin.apt:
        name:
          - software-properties-common
          - certbot
          - python3-certbot-dns-route53
        state: present

    - name: Obtain SSL certificate using Certbot
      ansible.builtin.command:
        cmd: >
          certbot certonly
          --dns-route53
          -d "{{ domain_name }}"
          -d "*.{{ domain_name }}"
          --non-interactive
          --agree-tos
          --email "{{ email }}"
      args:
        creates: "/etc/letsencrypt/live/{{ domain_name.strip('*.') }}"

    - name: Start Docker Compose
      ansible.builtin.command:
        cmd: docker compose -f docker-compose-monitoring.yaml up -d
        chdir: /app
      changed_when: false
